### ISSUE TITLE
Button 'Anlegen' erstellen, damit Artikel übermittelt und angelegt wird

### ISSUE THREAD

**Issue by hairyunicorn** [thomas-gantenbein-tga/sharingapp_clientside#18]
... sonst können wir nur mit der bestehenden DB arbeiten

**Comment by thomas-gantenbein-tga** [comment]
Das haben wir doch in #11 erledigt, oder?

**Comment by hairyunicorn** [comment]
Jetzt da du's erwähnst sehe ich es im Designer auch hat sich ganz
unscheinbar unten an die Kante geheftet. Wenn ich den Simulator starte,
erscheint der Button bei mir jedoch nicht - passt da was noch nicht ganz?
Ich sehe auch keinen Scroll-Balken am Rand.



Am So., 26. Aug. 2018 um 21:31 Uhr schrieb thomas-gantenbein-tga <
notifications@github.com>:

**Comment by thomas-gantenbein-tga** [comment]
Wenn du ihn fast nicht siehst, dann wird wohl was noch nicht ganz stimmen. Lass uns das morgen anschaun.

**Comment by hairyunicorn** [comment]
das wird morgen etwas schwierig - hättest du am dienstag zwischen 17 und 18
h auch zeit?



Am So., 26. Aug. 2018 um 21:49 Uhr schrieb thomas-gantenbein-tga <
notifications@github.com>:

**Comment by thomas-gantenbein-tga** [comment]
Leider nein. Ich schau mir das morgen an, hoffe, dass ich gleich sehe, was nicht passt, und lass es dich wissen. Ist das in Ordnung?

**Comment by hairyunicorn** [comment]
Geht auch, ich schaue mit etwas Abstand auch nochmals drüber

⁣Gesendet mit TypeApp ​

**Comment by hairyunicorn** [comment]
Hoi Thomas

ich habe mein Projekt wohl etwas verbogen - wenn ich einen neuen Pull
starten will, m die aktuelle Version zu erhalten, bekomme ich die Meldung:

Gt Pull Failed
You have not concluded your merge (MERGE_HEAD exists). Exiting because of
unfinished merge.


Ich kann das File im Filesystem zwar sehen, bin jetzt aber grad ein
bisschen ratlos - ich kann auch sehr gut damit leben, wenn ich die letzten
Änderungen verliere, das bekomme ich zügig wieder hin.

Hast du einen Tipp?

Grüsse

Martin

*martin herzog*

langwiesstrasse 14 · ch-8500 frauenfeld · +41 76 331 15 81


Am Mo., 27. Aug. 2018 um 20:25 Uhr schrieb thomas-gantenbein-tga <
notifications@github.com>:

**Comment by thomas-gantenbein-tga** [comment]
Hoi Martin
Hmm, vielleicht hilft das hier: https://stackoverflow.com/a/11647899
Oder auch: Die Nummer vom letzten Commit rausfinden, die noch funktioniert hat. Dann VCS - Git - Reset Head, beim Modus "Hard" wählen und im Feld Commit die Nummer eintragen.
Und wenn alles nichts hilft: https://stackoverflow.com/a/16797319. Danach das .git-Verzeichnis (ist dort, wo auch deine Projektdateien gespeichert sind) löschen und das Projekt neu klonen.
