### ISSUE TITLE
Artikel-Erfassen-Activity um Labels ergänzen

### ISSUE THREAD

**Issue by thomas-gantenbein-tga** [thomas-gantenbein-tga/sharingapp_clientside#2]
Hallo Martin, Nur ein Test und Vorschlag, um Aufgaben zu verteilen.

**Comment by thomas-gantenbein-tga** [comment]
@hairyunicorn: Commit https://github.com/thomas-gantenbein-tga/sharingapp_clientside/commit/2c54e8dff8de270e9c2e3b5f15695fc62546ce36 hat ein Beispiel drin, das dir vielleicht hilft, die Sache mit den Labeln hinzukriegen.

**Comment by hairyunicorn** [comment]
Sali Thomas

Dieses Problem habe ich heute Morgen erfolreich behoben.

Eigentlich wollte ich heute Nachmittag noch etwas weitermachen, wurde dann
aber vom Update-Prozess meiner IDE ausgebremst - die kommt irgendwie nicht
zum Abschluss und macht Ewigkeiten am letzten Patch-Teil 'rum.

Ich melde mich wieder mit den nächsten Schritten.

Grüsse

Martin

*martin herzog*

langwiesstrasse 14 · ch-8500 frauenfeld · +41 76 331 15 81


Am Do., 23. Aug. 2018 um 23:07 Uhr schrieb thomas-gantenbein-tga <
notifications@github.com>:
