### ISSUE TITLE
Bewertungskriterien auf Moodle anschaun und Tickets dazu erstellen

### ISSUE THREAD

**Issue by thomas-gantenbein-tga** [thomas-gantenbein-tga/sharingapp_clientside#35]

**Comment by hairyunicorn** [comment]
Bewertungskriterien analysiert und Issues erstellt, siehe
**sharingapp_clientside:**
- [App-Bewertung](https://github.com/thomas-gantenbein-tga/sharingapp_clientside/issues/46)
- [README-File überarbeiten](https://github.com/thomas-gantenbein-tga/sharingapp_clientside/issues/45)
- [Vortragsfolien für 10 - 15 Minuten Präsentationsdauer (Gewichtung 1)](https://github.com/thomas-gantenbein-tga/sharingapp_clientside/issues/44)

**sharingapp_serverside:**
- [README-File überarbeiten](https://github.com/thomas-gantenbein-tga/sharingapp_serverside/issues/2)
