### ISSUE TITLE
Artikel erfassen: Kategorie als Dropdown

### ISSUE THREAD

**Issue by thomas-gantenbein-tga** [thomas-gantenbein-tga/sharingapp_clientside#4]
Bei der Kategorie würde ich ein Dropdown vorsehen.

**Comment by hairyunicorn** [comment]
Guter Input, werde ich entsprechend umsetzten. Auf die Schnelle hat's leider nur mit den künftigen Werten geklappt, der Spinner ziert sich noch ...

**Comment by hairyunicorn** [comment]
@thomas-gantenbein-tga: Wenn du hier schon eine Idee hast, nur her damti
